<?xml version="1.0"?>
<robot name="gripper" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="gripper_camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/rrbot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base"/>
  </joint>

  <!-- Base Link -->
  <link name="base">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/Base.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="orange"/>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/Base.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <!-- Middle Link -->
  <link name="left_servo">
    <collision>
      <origin xyz="-0.0375 0 0.104075" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/RX-64.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="red"/>
    </collision>

    <visual>
      <origin xyz="-0.0375 0 0.104075" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/RX-64.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="L_S" type="fixed">
    <parent link="base"/>
    <child link="left_servo"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  
  <link name="right_servo">
    <collision>
      <origin xyz="0.0375 0 0.104075" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/RX-64.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="red"/>
    </collision>

    <visual>
      <origin xyz="0.0375 0 0.104075" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/RX-64.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="R_S" type="fixed">
    <parent link="base"/>
    <child link="right_servo"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  
  
  <link name="claw_b">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/claw_b.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/claw_b.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="left_servo"/>
    <child link="claw_b"/>
    <origin xyz="0.0375 0.0 0.104075" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  
  <link name="claw_a">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/claw_a.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
      <geometry>
	<mesh filename="package://rrbot_description/meshes/claw_a.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="right_servo"/>
    <child link="claw_a"/>
    <origin xyz="-0.0375 0.0 0.104075" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  
  
  <joint name="gripper_camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 0.12" rpy="0 0 0"/>
    <parent link="base"/>	
    <child link="gripper_camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="gripper_camera_link">
    <collision>
      <origin xyz="0 0 -0.025" rpy="0 0 0"/>
      <geometry>
	<cylinder length="0.005" radius="0.015"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 -0.01" rpy="0 0 0"/>
      <geometry>
     	<cylinder length="0.005" radius="0.012"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->
  <joint name="gripper_camera_optical_joint" type="fixed">
    <!-- these values have to be these values otherwise the gazebo camera image
        won't be aligned properly with the frame it is supposedly originating from -->
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="gripper_camera_link"/>
    <child link="gripper_camera_link_optical"/>
  </joint>

  <link name="gripper_camera_link_optical">
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/gripper</robotNamespace>
    </plugin>
  </gazebo>  -->

</robot>
